// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::context::{LoadContext, SaveContext};

/// Ranked normalized screenshot point used for camera moves.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct MotionPoint {
    /// 1, 2, or 3.
    pub rank: i32,
    pub x: f32,
    pub y: f32,
    pub label: Option<String>,
}

impl MotionPoint {
    /// Create a new MotionPoint with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load MotionPoint from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load MotionPoint from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load MotionPoint from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load MotionPoint from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            rank: value.get("rank").and_then(|v| v.as_i64()).unwrap_or(0) as i32,
            x: value.get("x").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32,
            y: value.get("y").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32,
            label: value.get("label").and_then(|v| v.as_str()).map(|s| s.to_string()),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }

    /// Serialize MotionPoint to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        result.insert("rank".to_string(), serde_json::Value::Number(serde_json::Number::from(self.rank)));
        result.insert("x".to_string(), serde_json::Number::from_f64(self.x as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        result.insert("y".to_string(), serde_json::Number::from_f64(self.y as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        if let Some(val) = self.label.as_ref() {
            result.insert("label".to_string(), serde_json::Value::String(val.clone()));
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize MotionPoint to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize MotionPoint to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
}

// Serde for `MotionPoint` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for MotionPoint {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for MotionPoint {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
