// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::context::{LoadContext, SaveContext};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MotionPlanEasing {
    Linear,
    Ease_in_out,
    Ease_out,
}

impl Default for MotionPlanEasing {
    fn default() -> Self {
        Self::Linear
    }
}

impl std::fmt::Display for MotionPlanEasing {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Linear => write!(f, "linear"),
            Self::Ease_in_out => write!(f, "ease_in_out"),
            Self::Ease_out => write!(f, "ease_out"),
        }
    }
}

impl MotionPlanEasing {
    pub fn from_str_opt(s: &str) -> Option<Self> {
        match s {
            "linear" => Some(Self::Linear),
            "ease_in_out" => Some(Self::Ease_in_out),
            "ease_out" => Some(Self::Ease_out),
            _ => None,
        }
    }

    pub fn from_str_ignore_case_opt(s: &str) -> Option<Self> {
        if s.eq_ignore_ascii_case("linear") {
            return Some(Self::Linear);
        }
        if s.eq_ignore_ascii_case("ease_in_out") {
            return Some(Self::Ease_in_out);
        }
        if s.eq_ignore_ascii_case("ease_out") {
            return Some(Self::Ease_out);
        }
        None
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::Linear => "linear",
            Self::Ease_in_out => "ease_in_out",
            Self::Ease_out => "ease_out",
        }
    }
}

#[cfg(feature = "serde")]
impl serde::Serialize for MotionPlanEasing {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for MotionPlanEasing {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(deserializer)?;
        Self::from_str_opt(&s)
            .ok_or_else(|| serde::de::Error::custom(format!("invalid MotionPlanEasing value: {}", s)))
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct MotionPlanKeyframe {
    pub time_ms: i64,
    pub scale: f32,
    pub x: f32,
    pub y: f32,
    pub easing: Option<MotionPlanEasing>,
}

impl MotionPlanKeyframe {
    /// Create a new MotionPlanKeyframe with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load MotionPlanKeyframe from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load MotionPlanKeyframe from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load MotionPlanKeyframe from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load MotionPlanKeyframe from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            time_ms: value.get("time_ms").and_then(|v| v.as_i64()).unwrap_or(0),
            scale: value.get("scale").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32,
            x: value.get("x").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32,
            y: value.get("y").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32,
            easing: value.get("easing").and_then(|v| v.as_str()).and_then(|s| MotionPlanEasing::from_str_opt(s)),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }

    /// Serialize MotionPlanKeyframe to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        result.insert("time_ms".to_string(), serde_json::Value::Number(serde_json::Number::from(self.time_ms)));
        result.insert("scale".to_string(), serde_json::Number::from_f64(self.scale as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        result.insert("x".to_string(), serde_json::Number::from_f64(self.x as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        result.insert("y".to_string(), serde_json::Number::from_f64(self.y as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        if let Some(val) = self.easing.as_ref() {
            result.insert("easing".to_string(), serde_json::Value::String(val.to_string()));
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize MotionPlanKeyframe to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize MotionPlanKeyframe to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
}

// Serde for `MotionPlanKeyframe` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for MotionPlanKeyframe {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for MotionPlanKeyframe {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
