// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::context::{LoadContext, SaveContext};

/// A deliberate delivery beat for generated narration.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct NarrationBeat {
    pub text: String,
    pub purpose: Option<String>,
    pub style: Option<String>,
    pub style_degree: Option<f32>,
    pub emphasis: Option<String>,
    pub pause_after_ms: Option<i64>,
}

impl NarrationBeat {
    /// Create a new NarrationBeat with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load NarrationBeat from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load NarrationBeat from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load NarrationBeat from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load NarrationBeat from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            text: value.get("text").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            purpose: value.get("purpose").and_then(|v| v.as_str()).map(|s| s.to_string()),
            style: value.get("style").and_then(|v| v.as_str()).map(|s| s.to_string()),
            style_degree: value.get("style_degree").and_then(|v| v.as_f64()).map(|v| v as f32),
            emphasis: value.get("emphasis").and_then(|v| v.as_str()).map(|s| s.to_string()),
            pause_after_ms: value.get("pause_after_ms").and_then(|v| v.as_i64()),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }

    /// Serialize NarrationBeat to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        result.insert("text".to_string(), serde_json::Value::String(self.text.clone()));
        if let Some(val) = self.purpose.as_ref() {
            result.insert("purpose".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.style.as_ref() {
            result.insert("style".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.style_degree.as_ref() {
            result.insert("style_degree".to_string(), serde_json::Number::from_f64(*val as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        }
        if let Some(val) = self.emphasis.as_ref() {
            result.insert("emphasis".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.pause_after_ms.as_ref() {
            result.insert("pause_after_ms".to_string(), serde_json::Value::Number(serde_json::Number::from(*val)));
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize NarrationBeat to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize NarrationBeat to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
}

// Serde for `NarrationBeat` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for NarrationBeat {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for NarrationBeat {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
