// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::context::{LoadContext, SaveContext};

use super::narration_beat::NarrationBeat;

/// Durable creative direction and compiled SSML for generated narration.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct NarrationPlan {
    pub source_text: String,
    pub voice: String,
    pub locale: String,
    pub ssml: String,
    pub baseline_style: Option<String>,
    pub pronunciation_overrides: Option<std::collections::HashMap<String, String>>,
    pub beats: Option<Vec<NarrationBeat>>,
    /// RFC 3339 UTC timestamp.
    pub generated_at: String,
}

impl NarrationPlan {
    /// Create a new NarrationPlan with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load NarrationPlan from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load NarrationPlan from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load NarrationPlan from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load NarrationPlan from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            source_text: value.get("source_text").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            voice: value.get("voice").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            locale: value.get("locale").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            ssml: value.get("ssml").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            baseline_style: value.get("baseline_style").and_then(|v| v.as_str()).map(|s| s.to_string()),
            pronunciation_overrides: value.get("pronunciation_overrides").and_then(|v| v.as_object()).map(|items| items.iter().map(|(key, item)| (key.clone(), item.as_str().unwrap_or_default().to_string())).collect()),
            beats: value.get("beats").map(|v| Self::load_beats(v, ctx)),
            generated_at: value.get("generated_at").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        if let Some(entries) = value.get("beats").and_then(|candidate| candidate.as_array()) {
            let collection_path = if path.is_empty() { "beats".to_string() } else { format!("{}.beats", path) };
            for (index, entry) in entries.iter().enumerate() {
                let entry_path = format!("{}[{}]", collection_path, index);
                NarrationBeat::validate_input_at(entry, &entry_path)?;
            }
        }
        Ok(())
    }

    /// Serialize NarrationPlan to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        result.insert("source_text".to_string(), serde_json::Value::String(self.source_text.clone()));
        result.insert("voice".to_string(), serde_json::Value::String(self.voice.clone()));
        result.insert("locale".to_string(), serde_json::Value::String(self.locale.clone()));
        result.insert("ssml".to_string(), serde_json::Value::String(self.ssml.clone()));
        if let Some(val) = self.baseline_style.as_ref() {
            result.insert("baseline_style".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(items) = self.pronunciation_overrides.as_ref() {
            result.insert("pronunciation_overrides".to_string(), serde_json::to_value(items).unwrap_or(serde_json::Value::Null));
        }
        if let Some(items) = self.beats.as_ref() {
            result.insert("beats".to_string(), Self::save_beats(items, ctx));
        }
        result.insert("generated_at".to_string(), serde_json::Value::String(self.generated_at.clone()));
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize NarrationPlan to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize NarrationPlan to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }

    /// Load a collection of NarrationBeat from a JSON value.
    /// Handles both array format `[{...}]`.
    fn load_beats(data: &serde_json::Value, ctx: &LoadContext) -> Vec<NarrationBeat> {
        match data {
            serde_json::Value::Array(arr) => {
                arr.iter().map(|v| NarrationBeat::load_from_value(v, ctx)).collect()
            }

            _ => Vec::new(),

        }
    }

    /// Save a collection of NarrationBeat to a JSON value.
    fn save_beats(items: &[NarrationBeat], ctx: &SaveContext) -> serde_json::Value {

        serde_json::Value::Array(items.iter().map(|item| item.to_value(ctx)).collect::<Vec<_>>())

    }
}

// Serde for `NarrationPlan` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for NarrationPlan {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for NarrationPlan {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
