// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::context::{LoadContext, SaveContext};

/// Recorded or generated narration audio attached to a row.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct NarrationAsset {
    pub path: String,
    /// Narrative text at the moment the audio was recorded or generated.
    pub source_text: String,
    /// SHA-256 of `source_text`.
    pub source_text_hash: String,
    pub mime_type: String,
    /// Canonical save writes `null` when unknown.
    pub duration_ms: Option<i64>,
    pub leading_silence_ms: Option<i64>,
    pub trailing_silence_ms: Option<i64>,
    pub silence_threshold_db: Option<f32>,
    pub byte_size: i64,
    /// RFC 3339 UTC timestamp.
    pub recorded_at: String,
}

impl NarrationAsset {
    /// Create a new NarrationAsset with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load NarrationAsset from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load NarrationAsset from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load NarrationAsset from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load NarrationAsset from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            path: value.get("path").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            source_text: value.get("source_text").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            source_text_hash: value.get("source_text_hash").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            mime_type: value.get("mime_type").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            duration_ms: value.get("duration_ms").and_then(|v| v.as_i64()),
            leading_silence_ms: value.get("leading_silence_ms").and_then(|v| v.as_i64()),
            trailing_silence_ms: value.get("trailing_silence_ms").and_then(|v| v.as_i64()),
            silence_threshold_db: value.get("silence_threshold_db").and_then(|v| v.as_f64()).map(|v| v as f32),
            byte_size: value.get("byte_size").and_then(|v| v.as_i64()).unwrap_or(0),
            recorded_at: value.get("recorded_at").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }

    /// Serialize NarrationAsset to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        result.insert("path".to_string(), serde_json::Value::String(self.path.clone()));
        result.insert("source_text".to_string(), serde_json::Value::String(self.source_text.clone()));
        result.insert("source_text_hash".to_string(), serde_json::Value::String(self.source_text_hash.clone()));
        result.insert("mime_type".to_string(), serde_json::Value::String(self.mime_type.clone()));
        if let Some(val) = self.duration_ms.as_ref() {
            result.insert("duration_ms".to_string(), serde_json::Value::Number(serde_json::Number::from(*val)));
        }
        if let Some(val) = self.leading_silence_ms.as_ref() {
            result.insert("leading_silence_ms".to_string(), serde_json::Value::Number(serde_json::Number::from(*val)));
        }
        if let Some(val) = self.trailing_silence_ms.as_ref() {
            result.insert("trailing_silence_ms".to_string(), serde_json::Value::Number(serde_json::Number::from(*val)));
        }
        if let Some(val) = self.silence_threshold_db.as_ref() {
            result.insert("silence_threshold_db".to_string(), serde_json::Number::from_f64(*val as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        }
        result.insert("byte_size".to_string(), serde_json::Value::Number(serde_json::Number::from(self.byte_size)));
        result.insert("recorded_at".to_string(), serde_json::Value::String(self.recorded_at.clone()));
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize NarrationAsset to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize NarrationAsset to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
}

// Serde for `NarrationAsset` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for NarrationAsset {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for NarrationAsset {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
