// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::context::{LoadContext, SaveContext};

use super::motion_plan::MotionPlan;

use super::motion_point::MotionPoint;

use super::narration_asset::NarrationAsset;

use super::narration_plan::NarrationPlan;

use super::planning_cell_locks::PlanningCellLocks;

use super::typing_spot::TypingSpot;

/// A row in the sketch planning table. Unknown fields must survive every runtime's decode -> save.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct PlanningRow {
    /// Whether the entire row is protected from edits. Saved as `false` when unset.
    pub locked: Option<bool>,
    /// Saved with all six fields, even when nothing is locked.
    pub locks: Option<PlanningCellLocks>,
    /// Human duration such as `~30s`, `0:20`, or `2m`.
    pub time: String,
    /// Concrete duration in seconds.
    pub duration_seconds: Option<i32>,
    pub narrative: String,
    pub demo_actions: String,
    /// Project-relative screenshot path. Canonical save writes `null` when absent.
    pub screenshot: Option<String>,
    /// Project-relative Elucim visual path (legacy files may inline the document). Opaque.
    pub visual: Option<serde_json::Value>,
    pub motion_points: Option<Vec<MotionPoint>>,
    pub typing_spots: Option<Vec<TypingSpot>>,
    pub motion_plan: Option<MotionPlan>,
    /// Designer brief for the visual.
    pub design_plan: Option<String>,
    pub narration: Option<NarrationAsset>,
    pub narration_plan: Option<NarrationPlan>,
}

impl PlanningRow {
    /// Create a new PlanningRow with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load PlanningRow from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load PlanningRow from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load PlanningRow from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load PlanningRow from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            locked: value.get("locked").and_then(|v| v.as_bool()),
            locks: value.get("locks").filter(|v| v.is_object() || v.is_array() || v.is_string()).map(|v| PlanningCellLocks::load_from_value(v, ctx)),
            time: value.get("time").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            duration_seconds: value.get("duration_seconds").and_then(|v| v.as_i64()).map(|v| v as i32),
            narrative: value.get("narrative").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            demo_actions: value.get("demo_actions").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            screenshot: value.get("screenshot").and_then(|v| v.as_str()).map(|s| s.to_string()),
            visual: value.get("visual").cloned(),
            motion_points: value.get("motion_points").map(|v| Self::load_motion_points(v, ctx)),
            typing_spots: value.get("typing_spots").map(|v| Self::load_typing_spots(v, ctx)),
            motion_plan: value.get("motion_plan").filter(|v| v.is_object() || v.is_array() || v.is_string()).map(|v| MotionPlan::load_from_value(v, ctx)),
            design_plan: value.get("design_plan").and_then(|v| v.as_str()).map(|s| s.to_string()),
            narration: value.get("narration").filter(|v| v.is_object() || v.is_array() || v.is_string()).map(|v| NarrationAsset::load_from_value(v, ctx)),
            narration_plan: value.get("narration_plan").filter(|v| v.is_object() || v.is_array() || v.is_string()).map(|v| NarrationPlan::load_from_value(v, ctx)),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        let child_path = if path.is_empty() { "locks".to_string() } else { format!("{}.locks", path) };
        if let Some(child) = value.get("locks") {
            PlanningCellLocks::validate_input_at(child, &child_path)?;
        }
        if let Some(entries) = value.get("motion_points").and_then(|candidate| candidate.as_array()) {
            let collection_path = if path.is_empty() { "motion_points".to_string() } else { format!("{}.motion_points", path) };
            for (index, entry) in entries.iter().enumerate() {
                let entry_path = format!("{}[{}]", collection_path, index);
                MotionPoint::validate_input_at(entry, &entry_path)?;
            }
        }
        if let Some(entries) = value.get("typing_spots").and_then(|candidate| candidate.as_array()) {
            let collection_path = if path.is_empty() { "typing_spots".to_string() } else { format!("{}.typing_spots", path) };
            for (index, entry) in entries.iter().enumerate() {
                let entry_path = format!("{}[{}]", collection_path, index);
                TypingSpot::validate_input_at(entry, &entry_path)?;
            }
        }
        let child_path = if path.is_empty() { "motion_plan".to_string() } else { format!("{}.motion_plan", path) };
        if let Some(child) = value.get("motion_plan") {
            MotionPlan::validate_input_at(child, &child_path)?;
        }
        let child_path = if path.is_empty() { "narration".to_string() } else { format!("{}.narration", path) };
        if let Some(child) = value.get("narration") {
            NarrationAsset::validate_input_at(child, &child_path)?;
        }
        let child_path = if path.is_empty() { "narration_plan".to_string() } else { format!("{}.narration_plan", path) };
        if let Some(child) = value.get("narration_plan") {
            NarrationPlan::validate_input_at(child, &child_path)?;
        }
        Ok(())
    }

    /// Serialize PlanningRow to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        if let Some(val) = self.locked.as_ref() {
            result.insert("locked".to_string(), serde_json::Value::Bool(*val));
        }
        if let Some(val) = self.locks.as_ref() {
            let nested = val.to_value(ctx);
            if !nested.is_null() {
                result.insert("locks".to_string(), nested);
            }
        }
        result.insert("time".to_string(), serde_json::Value::String(self.time.clone()));
        if let Some(val) = self.duration_seconds.as_ref() {
            result.insert("duration_seconds".to_string(), serde_json::Value::Number(serde_json::Number::from(*val)));
        }
        result.insert("narrative".to_string(), serde_json::Value::String(self.narrative.clone()));
        result.insert("demo_actions".to_string(), serde_json::Value::String(self.demo_actions.clone()));
        if let Some(val) = self.screenshot.as_ref() {
            result.insert("screenshot".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.visual.as_ref() {
            result.insert("visual".to_string(), val.clone());
        }
        if let Some(items) = self.motion_points.as_ref() {
            result.insert("motion_points".to_string(), Self::save_motion_points(items, ctx));
        }
        if let Some(items) = self.typing_spots.as_ref() {
            result.insert("typing_spots".to_string(), Self::save_typing_spots(items, ctx));
        }
        if let Some(val) = self.motion_plan.as_ref() {
            let nested = val.to_value(ctx);
            if !nested.is_null() {
                result.insert("motion_plan".to_string(), nested);
            }
        }
        if let Some(val) = self.design_plan.as_ref() {
            result.insert("design_plan".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.narration.as_ref() {
            let nested = val.to_value(ctx);
            if !nested.is_null() {
                result.insert("narration".to_string(), nested);
            }
        }
        if let Some(val) = self.narration_plan.as_ref() {
            let nested = val.to_value(ctx);
            if !nested.is_null() {
                result.insert("narration_plan".to_string(), nested);
            }
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize PlanningRow to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize PlanningRow to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }

    /// Load a collection of MotionPoint from a JSON value.
    /// Handles both array format `[{...}]`.
    fn load_motion_points(data: &serde_json::Value, ctx: &LoadContext) -> Vec<MotionPoint> {
        match data {
            serde_json::Value::Array(arr) => {
                arr.iter().map(|v| MotionPoint::load_from_value(v, ctx)).collect()
            }

            _ => Vec::new(),

        }
    }

    /// Save a collection of MotionPoint to a JSON value.
    fn save_motion_points(items: &[MotionPoint], ctx: &SaveContext) -> serde_json::Value {

        serde_json::Value::Array(items.iter().map(|item| item.to_value(ctx)).collect::<Vec<_>>())

    }

    /// Load a collection of TypingSpot from a JSON value.
    /// Handles both array format `[{...}]`.
    fn load_typing_spots(data: &serde_json::Value, ctx: &LoadContext) -> Vec<TypingSpot> {
        match data {
            serde_json::Value::Array(arr) => {
                arr.iter().map(|v| TypingSpot::load_from_value(v, ctx)).collect()
            }

            _ => Vec::new(),

        }
    }

    /// Save a collection of TypingSpot to a JSON value.
    fn save_typing_spots(items: &[TypingSpot], ctx: &SaveContext) -> serde_json::Value {

        serde_json::Value::Array(items.iter().map(|item| item.to_value(ctx)).collect::<Vec<_>>())

    }
}

// Serde for `PlanningRow` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for PlanningRow {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for PlanningRow {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
