// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::context::{LoadContext, SaveContext};

use super::document_metadata::DocumentMetadata;

use super::planning_row::PlanningRow;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SketchState {
    Draft,
    Recording_enriched,
    Refined,
    Final,
}

impl Default for SketchState {
    fn default() -> Self {
        Self::Draft
    }
}

impl std::fmt::Display for SketchState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Draft => write!(f, "draft"),
            Self::Recording_enriched => write!(f, "recording_enriched"),
            Self::Refined => write!(f, "refined"),
            Self::Final => write!(f, "final"),
        }
    }
}

impl SketchState {
    pub fn from_str_opt(s: &str) -> Option<Self> {
        match s {
            "draft" => Some(Self::Draft),
            "recording_enriched" => Some(Self::Recording_enriched),
            "refined" => Some(Self::Refined),
            "final" => Some(Self::Final),
            "sketch" => Some(Self::Draft),
            _ => None,
        }
    }

    pub fn from_str_ignore_case_opt(s: &str) -> Option<Self> {
        if s.eq_ignore_ascii_case("draft") {
            return Some(Self::Draft);
        }
        if s.eq_ignore_ascii_case("recording_enriched") {
            return Some(Self::Recording_enriched);
        }
        if s.eq_ignore_ascii_case("refined") {
            return Some(Self::Refined);
        }
        if s.eq_ignore_ascii_case("final") {
            return Some(Self::Final);
        }
        if s.eq_ignore_ascii_case("sketch") {
            return Some(Self::Draft);
        }
        None
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::Draft => "draft",
            Self::Recording_enriched => "recording_enriched",
            Self::Refined => "refined",
            Self::Final => "final",
        }
    }
}

#[cfg(feature = "serde")]
impl serde::Serialize for SketchState {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for SketchState {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(deserializer)?;
        Self::from_str_opt(&s)
            .ok_or_else(|| serde::de::Error::custom(format!("invalid SketchState value: {}", s)))
    }
}

/// A `.sk` file: a focused scene with a planning table. Unknown top-level fields must survive every runtime's decode -> save.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Sketch {
    pub title: String,
    /// Whether the whole sketch is protected from edits. Saved as `false` when unset.
    pub locked: Option<bool>,
    /// Rich-text description (Lexical JSON, Markdown string, or null). Opaque.
    pub description: Option<serde_json::Value>,
    pub rows: Vec<PlanningRow>,
    pub metadata: Option<DocumentMetadata>,
    pub state: SketchState,
    /// RFC 3339 UTC timestamp. Runtimes never rewrite a timestamp they did not change.
    pub created_at: String,
    /// RFC 3339 UTC timestamp, set by every successful edit.
    pub updated_at: String,
}

impl Sketch {
    /// Create a new Sketch with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load Sketch from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load Sketch from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load Sketch from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load Sketch from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            title: value.get("title").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            locked: value.get("locked").and_then(|v| v.as_bool()),
            description: value.get("description").cloned(),
            rows: value.get("rows").map(|v| Self::load_rows(v, ctx)).unwrap_or_default(),
            metadata: value.get("metadata").filter(|v| v.is_object() || v.is_array() || v.is_string()).map(|v| DocumentMetadata::load_from_value(v, ctx)),
            state: value.get("state").and_then(|v| v.as_str()).and_then(|s| SketchState::from_str_opt(s)).unwrap_or(SketchState::Draft),
            created_at: value.get("created_at").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            updated_at: value.get("updated_at").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        if let Some(entries) = value.get("rows").and_then(|candidate| candidate.as_array()) {
            let collection_path = if path.is_empty() { "rows".to_string() } else { format!("{}.rows", path) };
            for (index, entry) in entries.iter().enumerate() {
                let entry_path = format!("{}[{}]", collection_path, index);
                PlanningRow::validate_input_at(entry, &entry_path)?;
            }
        }
        let child_path = if path.is_empty() { "metadata".to_string() } else { format!("{}.metadata", path) };
        if let Some(child) = value.get("metadata") {
            DocumentMetadata::validate_input_at(child, &child_path)?;
        }
        Ok(())
    }

    /// Serialize Sketch to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        result.insert("title".to_string(), serde_json::Value::String(self.title.clone()));
        if let Some(val) = self.locked.as_ref() {
            result.insert("locked".to_string(), serde_json::Value::Bool(*val));
        }
        if let Some(val) = self.description.as_ref() {
            result.insert("description".to_string(), val.clone());
        }
        result.insert("rows".to_string(), Self::save_rows(&self.rows, ctx));
        if let Some(val) = self.metadata.as_ref() {
            let nested = val.to_value(ctx);
            if !nested.is_null() {
                result.insert("metadata".to_string(), nested);
            }
        }
        result.insert("state".to_string(), serde_json::Value::String(self.state.to_string()));
        result.insert("created_at".to_string(), serde_json::Value::String(self.created_at.clone()));
        result.insert("updated_at".to_string(), serde_json::Value::String(self.updated_at.clone()));
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize Sketch to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize Sketch to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }

    /// Load a collection of PlanningRow from a JSON value.
    /// Handles both array format `[{...}]`.
    fn load_rows(data: &serde_json::Value, ctx: &LoadContext) -> Vec<PlanningRow> {
        match data {
            serde_json::Value::Array(arr) => {
                arr.iter().map(|v| PlanningRow::load_from_value(v, ctx)).collect()
            }

            _ => Vec::new(),

        }
    }

    /// Save a collection of PlanningRow to a JSON value.
    fn save_rows(items: &[PlanningRow], ctx: &SaveContext) -> serde_json::Value {

        serde_json::Value::Array(items.iter().map(|item| item.to_value(ctx)).collect::<Vec<_>>())

    }
}

// Serde for `Sketch` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for Sketch {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for Sketch {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
