// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]


use super::row_text_update::RowTextUpdate;

use super::sketch::Sketch;

/// Behavioral contract for `.sk` documents. Each runtime binds these operations to its production decode, edit, and save code through a thin vector adapter. Inputs and outputs are raw `.sk` JSON, so the vectors also prove that fields a runtime does not model survive the round trip. Successful edits set `updated_at` to `now` (RFC 3339, at most microsecond precision); rejected edits report a SketchEditError.
#[async_trait::async_trait]
pub trait SketchDocument: Send + Sync {
    /// Reorder rows. `order[i]` is the current zero-based index of the row that moves to position `i`.
    fn reorder_rows(&self, sketch: &Sketch, order: &Vec<i32>, now: &String) -> Sketch;
    /// Decode a `.sk` document and save it again without changes.
    fn round_trip(&self, sketch: &Sketch) -> Sketch;
    /// Replace text cells on one row.
    fn update_row_text(&self, sketch: &Sketch, update: &RowTextUpdate, now: &String) -> Sketch;
}
