// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::context::{LoadContext, SaveContext};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PlanningCellField {
    Time,
    Narrative,
    Demo_actions,
    Screenshot,
    Visual,
    Design_plan,
}

impl Default for PlanningCellField {
    fn default() -> Self {
        Self::Time
    }
}

impl std::fmt::Display for PlanningCellField {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Time => write!(f, "time"),
            Self::Narrative => write!(f, "narrative"),
            Self::Demo_actions => write!(f, "demo_actions"),
            Self::Screenshot => write!(f, "screenshot"),
            Self::Visual => write!(f, "visual"),
            Self::Design_plan => write!(f, "design_plan"),
        }
    }
}

impl PlanningCellField {
    pub fn from_str_opt(s: &str) -> Option<Self> {
        match s {
            "time" => Some(Self::Time),
            "narrative" => Some(Self::Narrative),
            "demo_actions" => Some(Self::Demo_actions),
            "screenshot" => Some(Self::Screenshot),
            "visual" => Some(Self::Visual),
            "design_plan" => Some(Self::Design_plan),
            _ => None,
        }
    }

    pub fn from_str_ignore_case_opt(s: &str) -> Option<Self> {
        if s.eq_ignore_ascii_case("time") {
            return Some(Self::Time);
        }
        if s.eq_ignore_ascii_case("narrative") {
            return Some(Self::Narrative);
        }
        if s.eq_ignore_ascii_case("demo_actions") {
            return Some(Self::Demo_actions);
        }
        if s.eq_ignore_ascii_case("screenshot") {
            return Some(Self::Screenshot);
        }
        if s.eq_ignore_ascii_case("visual") {
            return Some(Self::Visual);
        }
        if s.eq_ignore_ascii_case("design_plan") {
            return Some(Self::Design_plan);
        }
        None
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::Time => "time",
            Self::Narrative => "narrative",
            Self::Demo_actions => "demo_actions",
            Self::Screenshot => "screenshot",
            Self::Visual => "visual",
            Self::Design_plan => "design_plan",
        }
    }
}

#[cfg(feature = "serde")]
impl serde::Serialize for PlanningCellField {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for PlanningCellField {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(deserializer)?;
        Self::from_str_opt(&s)
            .ok_or_else(|| serde::de::Error::custom(format!("invalid PlanningCellField value: {}", s)))
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SketchEditErrorCode {
    Locked_document,
    Locked_row,
    Locked_cell,
    Row_not_found,
    Invalid_reorder,
}

impl Default for SketchEditErrorCode {
    fn default() -> Self {
        Self::Locked_document
    }
}

impl std::fmt::Display for SketchEditErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Locked_document => write!(f, "locked_document"),
            Self::Locked_row => write!(f, "locked_row"),
            Self::Locked_cell => write!(f, "locked_cell"),
            Self::Row_not_found => write!(f, "row_not_found"),
            Self::Invalid_reorder => write!(f, "invalid_reorder"),
        }
    }
}

impl SketchEditErrorCode {
    pub fn from_str_opt(s: &str) -> Option<Self> {
        match s {
            "locked_document" => Some(Self::Locked_document),
            "locked_row" => Some(Self::Locked_row),
            "locked_cell" => Some(Self::Locked_cell),
            "row_not_found" => Some(Self::Row_not_found),
            "invalid_reorder" => Some(Self::Invalid_reorder),
            _ => None,
        }
    }

    pub fn from_str_ignore_case_opt(s: &str) -> Option<Self> {
        if s.eq_ignore_ascii_case("locked_document") {
            return Some(Self::Locked_document);
        }
        if s.eq_ignore_ascii_case("locked_row") {
            return Some(Self::Locked_row);
        }
        if s.eq_ignore_ascii_case("locked_cell") {
            return Some(Self::Locked_cell);
        }
        if s.eq_ignore_ascii_case("row_not_found") {
            return Some(Self::Row_not_found);
        }
        if s.eq_ignore_ascii_case("invalid_reorder") {
            return Some(Self::Invalid_reorder);
        }
        None
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::Locked_document => "locked_document",
            Self::Locked_row => "locked_row",
            Self::Locked_cell => "locked_cell",
            Self::Row_not_found => "row_not_found",
            Self::Invalid_reorder => "invalid_reorder",
        }
    }
}

#[cfg(feature = "serde")]
impl serde::Serialize for SketchEditErrorCode {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for SketchEditErrorCode {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(deserializer)?;
        Self::from_str_opt(&s)
            .ok_or_else(|| serde::de::Error::custom(format!("invalid SketchEditErrorCode value: {}", s)))
    }
}

/// The error payload every runtime reports when it rejects an edit.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SketchEditError {
    pub code: SketchEditErrorCode,
    /// Zero-based row position, for row-scoped errors.
    pub row_index: Option<i32>,
    /// The locked cell, for `locked_cell`.
    pub field: Option<PlanningCellField>,
}

impl SketchEditError {
    /// Create a new SketchEditError with default values.
    pub fn new() -> Self {
        Self::default()
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }

}
