// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::context::{LoadContext, SaveContext};

/// A normalized text region rendered as a typewriter overlay.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct TypingSpot {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
    pub text: String,
    pub start_offset_ms: Option<i64>,
    pub duration_ms: Option<i64>,
    pub characters_per_second: Option<f32>,
    pub show_cursor: Option<bool>,
    pub text_color: Option<String>,
    pub font_family: Option<String>,
    pub font_scale: Option<f32>,
}

impl TypingSpot {
    /// Create a new TypingSpot with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load TypingSpot from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load TypingSpot from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load TypingSpot from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load TypingSpot from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            x: value.get("x").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32,
            y: value.get("y").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32,
            width: value.get("width").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32,
            height: value.get("height").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32,
            text: value.get("text").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            start_offset_ms: value.get("start_offset_ms").and_then(|v| v.as_i64()),
            duration_ms: value.get("duration_ms").and_then(|v| v.as_i64()),
            characters_per_second: value.get("characters_per_second").and_then(|v| v.as_f64()).map(|v| v as f32),
            show_cursor: value.get("show_cursor").and_then(|v| v.as_bool()),
            text_color: value.get("text_color").and_then(|v| v.as_str()).map(|s| s.to_string()),
            font_family: value.get("font_family").and_then(|v| v.as_str()).map(|s| s.to_string()),
            font_scale: value.get("font_scale").and_then(|v| v.as_f64()).map(|v| v as f32),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }

    /// Serialize TypingSpot to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        result.insert("x".to_string(), serde_json::Number::from_f64(self.x as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        result.insert("y".to_string(), serde_json::Number::from_f64(self.y as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        result.insert("width".to_string(), serde_json::Number::from_f64(self.width as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        result.insert("height".to_string(), serde_json::Number::from_f64(self.height as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        result.insert("text".to_string(), serde_json::Value::String(self.text.clone()));
        if let Some(val) = self.start_offset_ms.as_ref() {
            result.insert("start_offset_ms".to_string(), serde_json::Value::Number(serde_json::Number::from(*val)));
        }
        if let Some(val) = self.duration_ms.as_ref() {
            result.insert("duration_ms".to_string(), serde_json::Value::Number(serde_json::Number::from(*val)));
        }
        if let Some(val) = self.characters_per_second.as_ref() {
            result.insert("characters_per_second".to_string(), serde_json::Number::from_f64(*val as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        }
        if let Some(val) = self.show_cursor.as_ref() {
            result.insert("show_cursor".to_string(), serde_json::Value::Bool(*val));
        }
        if let Some(val) = self.text_color.as_ref() {
            result.insert("text_color".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.font_family.as_ref() {
            result.insert("font_family".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.font_scale.as_ref() {
            result.insert("font_scale".to_string(), serde_json::Number::from_f64(*val as f64).map(serde_json::Value::Number).unwrap_or(serde_json::Value::Null));
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize TypingSpot to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize TypingSpot to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
}

// Serde for `TypingSpot` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for TypingSpot {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for TypingSpot {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
