// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
//
// Typed @vector conformance entrypoints (issue #511 Cat 1). Each generic fn
// takes a consumer's REAL typed seam impl and runs the seam's baked-in vectors
// by calling trait methods directly — the idiomatic replacement for the
// stringly HashMap<&str, Adapter> runner + vector_adapters.rs registry. The
// `S: <Seam>` bound makes the compiler prove every op is implemented (E0046),
// so completeness is checked at COMPILE time, not by a runtime map lookup.
// References only the model crate + serde_json + std (no vector_adapters, so
// no cycle); emitted additively beside the stringly runner.
// See docs: reference/vector-conformance.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use serde_json::Value;

/// Typed @vector conformance for SketchDocument. Pass your real `impl SketchDocument`; the
/// `S: SketchDocument` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_sketch_document_conformance(&SketchDocumentImpl).await;` (or without `.await` when sync).
pub fn run_sketch_document_conformance<S: crate::model::SketchDocument + ?Sized>(seam: &S) {
    let ctx = crate::model::context::LoadContext::default();
    // vector: canonical desktop sketch is unchanged
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": {
    "root": {
      "children": [
        {
          "type": "paragraph",
          "children": [
            {
              "text": "Intro scene"
            }
          ]
        }
      ]
    }
  },
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:20",
      "duration_seconds": 20,
      "narrative": "Open the workspace.",
      "demo_actions": "Click **Open**.",
      "visual": ".cutready/visuals/abc123def456.json",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25,
          "label": "Open button"
        },
        {
          "rank": 2,
          "x": 0.75,
          "y": 0.5
        }
      ],
      "typing_spots": [
        {
          "x": 0.25,
          "y": 0.5,
          "width": 0.5,
          "height": 0.125,
          "text": "demo-project",
          "start_offset_ms": 300,
          "characters_per_second": 18.5,
          "show_cursor": true,
          "font_family": "mono",
          "font_scale": 1.25
        }
      ],
      "motion_plan": {
        "kind": "wide_hold_then_push",
        "keyframes": [
          {
            "time_ms": 0,
            "scale": 1.25,
            "x": 0.5,
            "y": 0.5,
            "easing": "linear"
          },
          {
            "time_ms": 1500,
            "scale": 1.75,
            "x": 0.5,
            "y": 0.25,
            "easing": "ease_in_out"
          }
        ],
        "rationale": "Hold wide, then push toward the Open button."
      },
      "design_plan": "Title card with the product name.",
      "narration": {
        "path": ".cutready/narration/row-1.wav",
        "source_text": "Open the workspace.",
        "source_text_hash": "4f1c2a",
        "mime_type": "audio/wav",
        "duration_ms": 4200,
        "leading_silence_ms": 120,
        "trailing_silence_ms": 80,
        "silence_threshold_db": -41.5,
        "byte_size": 4096,
        "recorded_at": "2026-06-28T20:05:00Z"
      },
      "narration_plan": {
        "source_text": "Open the workspace.",
        "voice": "en-US-Harper:MAI-Voice-2",
        "locale": "en-US",
        "ssml": "<speak>Open the workspace.</speak>",
        "baseline_style": "friendly",
        "pronunciation_overrides": {
          "CutReady": "cut ready"
        },
        "beats": [
          {
            "text": "Open the workspace.",
            "emphasis": "moderate",
            "style_degree": 1.5,
            "pause_after_ms": 250
          }
        ],
        "generated_at": "2026-06-28T20:06:00Z"
      }
    }
  ],
  "state": "refined",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "metadata": {
    "fields": {
      "audience": "developers"
    }
  }
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let actual = seam.round_trip(&sketch);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": {
    "root": {
      "children": [
        {
          "type": "paragraph",
          "children": [
            {
              "text": "Intro scene"
            }
          ]
        }
      ]
    }
  },
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:20",
      "duration_seconds": 20,
      "narrative": "Open the workspace.",
      "demo_actions": "Click **Open**.",
      "visual": ".cutready/visuals/abc123def456.json",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25,
          "label": "Open button"
        },
        {
          "rank": 2,
          "x": 0.75,
          "y": 0.5
        }
      ],
      "typing_spots": [
        {
          "x": 0.25,
          "y": 0.5,
          "width": 0.5,
          "height": 0.125,
          "text": "demo-project",
          "start_offset_ms": 300,
          "characters_per_second": 18.5,
          "show_cursor": true,
          "font_family": "mono",
          "font_scale": 1.25
        }
      ],
      "motion_plan": {
        "kind": "wide_hold_then_push",
        "keyframes": [
          {
            "time_ms": 0,
            "scale": 1.25,
            "x": 0.5,
            "y": 0.5,
            "easing": "linear"
          },
          {
            "time_ms": 1500,
            "scale": 1.75,
            "x": 0.5,
            "y": 0.25,
            "easing": "ease_in_out"
          }
        ],
        "rationale": "Hold wide, then push toward the Open button."
      },
      "design_plan": "Title card with the product name.",
      "narration": {
        "path": ".cutready/narration/row-1.wav",
        "source_text": "Open the workspace.",
        "source_text_hash": "4f1c2a",
        "mime_type": "audio/wav",
        "duration_ms": 4200,
        "leading_silence_ms": 120,
        "trailing_silence_ms": 80,
        "silence_threshold_db": -41.5,
        "byte_size": 4096,
        "recorded_at": "2026-06-28T20:05:00Z"
      },
      "narration_plan": {
        "source_text": "Open the workspace.",
        "voice": "en-US-Harper:MAI-Voice-2",
        "locale": "en-US",
        "ssml": "<speak>Open the workspace.</speak>",
        "baseline_style": "friendly",
        "pronunciation_overrides": {
          "CutReady": "cut ready"
        },
        "beats": [
          {
            "text": "Open the workspace.",
            "emphasis": "moderate",
            "style_degree": 1.5,
            "pause_after_ms": 250
          }
        ],
        "generated_at": "2026-06-28T20:06:00Z"
      }
    }
  ],
  "state": "refined",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "metadata": {
    "fields": {
      "audience": "developers"
    }
  }
}
"####,
            &ctx,
        )
        .expect("canonical desktop sketch is unchanged: expected parses");
        assert_eq!(actual, expected, "canonical desktop sketch is unchanged misrouted");
    }
    // skipped: earlier locked cell fires before a later locked row — expectedError on a @sync op has no typed error channel
    // vector: edit time keeps microseconds
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:10",
      "narrative": "First.",
      "demo_actions": "Open.",
      "future_row_field": "first"
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/second.png",
      "time": "0:20",
      "narrative": "Second.",
      "demo_actions": "Click."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z"
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let update = crate::model::RowTextUpdate::from_json(
            r####"
{
  "row_index": 1,
  "demo_actions": "Double-click."
}
"####,
            &ctx,
        )
        .expect("update parses");
        let now: String = serde_json::from_str(
            r####"
"2026-07-01T09:30:00.123456Z"
"####,
        )
        .expect("now parses");
        let actual = seam.update_row_text(&sketch, &update, &now);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:10",
      "narrative": "First.",
      "demo_actions": "Open.",
      "future_row_field": "first"
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/second.png",
      "time": "0:20",
      "narrative": "Second.",
      "demo_actions": "Double-click."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-07-01T09:30:00.123456Z"
}
"####,
            &ctx,
        )
        .expect("edit time keeps microseconds: expected parses");
        assert_eq!(actual, expected, "edit time keeps microseconds misrouted");
    }
    // vector: legacy minimal sketch gains canonical defaults
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Legacy",
  "rows": [
    {
      "time": "~30s",
      "narrative": "Legacy row.",
      "demo_actions": "",
      "narration": {
        "path": ".cutready/narration/row-1.wav",
        "source_text": "Open the workspace.",
        "source_text_hash": "4f1c2a",
        "mime_type": "audio/wav",
        "leading_silence_ms": 120,
        "trailing_silence_ms": 80,
        "silence_threshold_db": -41.5,
        "byte_size": 4096,
        "recorded_at": "2026-06-28T20:05:00Z"
      }
    }
  ],
  "state": "sketch",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z"
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let actual = seam.round_trip(&sketch);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Legacy",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "~30s",
      "narrative": "Legacy row.",
      "demo_actions": "",
      "narration": {
        "path": ".cutready/narration/row-1.wav",
        "source_text": "Open the workspace.",
        "source_text_hash": "4f1c2a",
        "mime_type": "audio/wav",
        "leading_silence_ms": 120,
        "trailing_silence_ms": 80,
        "silence_threshold_db": -41.5,
        "byte_size": 4096,
        "recorded_at": "2026-06-28T20:05:00Z",
        "duration_ms": null
      }
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z"
}
"####,
            &ctx,
        )
        .expect("legacy minimal sketch gains canonical defaults: expected parses");
        assert_eq!(actual, expected, "legacy minimal sketch gains canonical defaults misrouted");
    }
    // vector: locked cell accepts an unchanged value
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:10",
      "duration_seconds": 10,
      "narrative": "Open the app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:20",
      "narrative": "Locked narration.",
      "demo_actions": "Type a name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let update = crate::model::RowTextUpdate::from_json(
            r####"
{
  "row_index": 1,
  "narrative": "Locked narration."
}
"####,
            &ctx,
        )
        .expect("update parses");
        let now: String = serde_json::from_str(
            r####"
"2026-07-01T09:30:00Z"
"####,
        )
        .expect("now parses");
        let actual = seam.update_row_text(&sketch, &update, &now);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:10",
      "duration_seconds": 10,
      "narrative": "Open the app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:20",
      "narrative": "Locked narration.",
      "demo_actions": "Type a name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-07-01T09:30:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("locked cell accepts an unchanged value: expected parses");
        assert_eq!(actual, expected, "locked cell accepts an unchanged value misrouted");
    }
    // skipped: locked cell rejects a change — expectedError on a @sync op has no typed error channel
    // skipped: locked cells are checked in column order — expectedError on a @sync op has no typed error channel
    // skipped: locked row protects fields a runtime does not model — expectedError on a @sync op has no typed error channel
    // skipped: locked row rejects a change — expectedError on a @sync op has no typed error channel
    // skipped: locked sketch rejects every edit — expectedError on a @sync op has no typed error channel
    // skipped: locked sketch takes precedence over a missing row — expectedError on a @sync op has no typed error channel
    // skipped: locked sketch takes precedence over an invalid order — expectedError on a @sync op has no typed error channel
    // vector: narrative edit preserves desktop-only and unknown fields
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:10",
      "duration_seconds": 10,
      "narrative": "Open the app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:20",
      "narrative": "Locked narration.",
      "demo_actions": "Type a name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let update = crate::model::RowTextUpdate::from_json(
            r####"
{
  "row_index": 0,
  "narrative": "Open the CutReady app."
}
"####,
            &ctx,
        )
        .expect("update parses");
        let now: String = serde_json::from_str(
            r####"
"2026-07-01T09:30:00Z"
"####,
        )
        .expect("now parses");
        let actual = seam.update_row_text(&sketch, &update, &now);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:10",
      "duration_seconds": 10,
      "narrative": "Open the CutReady app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:20",
      "narrative": "Locked narration.",
      "demo_actions": "Type a name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-07-01T09:30:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("narrative edit preserves desktop-only and unknown fields: expected parses");
        assert_eq!(actual, expected, "narrative edit preserves desktop-only and unknown fields misrouted");
    }
    // vector: null and empty optional values are omitted
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:05",
      "duration_seconds": null,
      "narrative": "Sparse row.",
      "demo_actions": "Wait.",
      "visual": null,
      "design_plan": null,
      "motion_points": null,
      "typing_spots": [],
      "motion_plan": {
        "kind": "subtle_push",
        "keyframes": [],
        "rationale": null
      },
      "narration": {
        "path": ".cutready/narration/row-1.wav",
        "source_text": "Open the workspace.",
        "source_text_hash": "4f1c2a",
        "mime_type": "audio/wav",
        "duration_ms": null,
        "leading_silence_ms": null,
        "trailing_silence_ms": null,
        "silence_threshold_db": null,
        "byte_size": 4096,
        "recorded_at": "2026-06-28T20:05:00Z"
      },
      "narration_plan": {
        "source_text": "Sparse row.",
        "voice": "en-US-Harper:MAI-Voice-2",
        "locale": "en-US",
        "ssml": "<speak>Sparse row.</speak>",
        "baseline_style": null,
        "pronunciation_overrides": {},
        "beats": [],
        "generated_at": "2026-06-28T20:06:00Z"
      }
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "metadata": {
    "fields": {}
  }
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let actual = seam.round_trip(&sketch);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:05",
      "narrative": "Sparse row.",
      "demo_actions": "Wait.",
      "motion_plan": {
        "kind": "subtle_push"
      },
      "narration": {
        "path": ".cutready/narration/row-1.wav",
        "source_text": "Open the workspace.",
        "source_text_hash": "4f1c2a",
        "mime_type": "audio/wav",
        "duration_ms": null,
        "byte_size": 4096,
        "recorded_at": "2026-06-28T20:05:00Z"
      },
      "narration_plan": {
        "source_text": "Sparse row.",
        "voice": "en-US-Harper:MAI-Voice-2",
        "locale": "en-US",
        "ssml": "<speak>Sparse row.</speak>",
        "generated_at": "2026-06-28T20:06:00Z"
      }
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z"
}
"####,
            &ctx,
        )
        .expect("null and empty optional values are omitted: expected parses");
        assert_eq!(actual, expected, "null and empty optional values are omitted misrouted");
    }
    // vector: reorder around locked rows keeps locks in place
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:10",
      "duration_seconds": 10,
      "narrative": "Open the app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:20",
      "narrative": "Locked narration.",
      "demo_actions": "Type a name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:40",
      "narrative": "Spare.",
      "demo_actions": "Wrap up."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let order: Vec<i32> = serde_json::from_str(
            r####"
[
  3,
  1,
  2,
  0
]
"####,
        )
        .expect("order parses");
        let now: String = serde_json::from_str(
            r####"
"2026-07-01T09:30:00Z"
"####,
        )
        .expect("now parses");
        let actual = seam.reorder_rows(&sketch, &order, &now);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:40",
      "narrative": "Spare.",
      "demo_actions": "Wrap up."
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:20",
      "narrative": "Locked narration.",
      "demo_actions": "Type a name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:10",
      "duration_seconds": 10,
      "narrative": "Open the app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-07-01T09:30:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("reorder around locked rows keeps locks in place: expected parses");
        assert_eq!(actual, expected, "reorder around locked rows keeps locks in place misrouted");
    }
    // vector: reorder moves whole rows including unknown fields
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:10",
      "narrative": "First.",
      "demo_actions": "Open.",
      "future_row_field": "first"
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/second.png",
      "time": "0:20",
      "narrative": "Second.",
      "demo_actions": "Click."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z"
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let order: Vec<i32> = serde_json::from_str(
            r####"
[
  1,
  0
]
"####,
        )
        .expect("order parses");
        let now: String = serde_json::from_str(
            r####"
"2026-07-01T09:30:00Z"
"####,
        )
        .expect("now parses");
        let actual = seam.reorder_rows(&sketch, &order, &now);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/second.png",
      "time": "0:20",
      "narrative": "Second.",
      "demo_actions": "Click."
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:10",
      "narrative": "First.",
      "demo_actions": "Open.",
      "future_row_field": "first"
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-07-01T09:30:00Z"
}
"####,
            &ctx,
        )
        .expect("reorder moves whole rows including unknown fields: expected parses");
        assert_eq!(actual, expected, "reorder moves whole rows including unknown fields misrouted");
    }
    // skipped: reorder that changes a locked cell is rejected — expectedError on a @sync op has no typed error channel
    // skipped: reorder that changes a locked row is rejected — expectedError on a @sync op has no typed error channel
    // skipped: reorder that is not a permutation is rejected — expectedError on a @sync op has no typed error channel
    // skipped: row index outside the table is rejected — expectedError on a @sync op has no typed error channel
    // skipped: row lock takes precedence over a cell lock — expectedError on a @sync op has no typed error channel
    // skipped: screenshot lock also guards the visual — expectedError on a @sync op has no typed error channel
    // vector: time edit leaves duration_seconds untouched
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:10",
      "duration_seconds": 10,
      "narrative": "Open the app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:20",
      "narrative": "Locked narration.",
      "demo_actions": "Type a name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let update = crate::model::RowTextUpdate::from_json(
            r####"
{
  "row_index": 0,
  "time": "0:15"
}
"####,
            &ctx,
        )
        .expect("update parses");
        let now: String = serde_json::from_str(
            r####"
"2026-07-01T09:30:00Z"
"####,
        )
        .expect("now parses");
        let actual = seam.update_row_text(&sketch, &update, &now);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:15",
      "duration_seconds": 10,
      "narrative": "Open the app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:20",
      "narrative": "Locked narration.",
      "demo_actions": "Type a name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-07-01T09:30:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("time edit leaves duration_seconds untouched: expected parses");
        assert_eq!(actual, expected, "time edit leaves duration_seconds untouched misrouted");
    }
    // vector: timestamps are saved as UTC
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:05",
      "narrative": "Offset.",
      "demo_actions": "",
      "narration": {
        "path": ".cutready/narration/row-1.wav",
        "source_text": "Open the workspace.",
        "source_text_hash": "4f1c2a",
        "mime_type": "audio/wav",
        "duration_ms": 4200,
        "leading_silence_ms": 120,
        "trailing_silence_ms": 80,
        "silence_threshold_db": -41.5,
        "byte_size": 4096,
        "recorded_at": "2026-06-28T22:05:00.5+02:00"
      }
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T22:00:00+02:00",
  "updated_at": "2026-06-28T20:20:00.123456789Z"
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let actual = seam.round_trip(&sketch);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:05",
      "narrative": "Offset.",
      "demo_actions": "",
      "narration": {
        "path": ".cutready/narration/row-1.wav",
        "source_text": "Open the workspace.",
        "source_text_hash": "4f1c2a",
        "mime_type": "audio/wav",
        "duration_ms": 4200,
        "leading_silence_ms": 120,
        "trailing_silence_ms": 80,
        "silence_threshold_db": -41.5,
        "byte_size": 4096,
        "recorded_at": "2026-06-28T20:05:00.500Z"
      }
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00.123456789Z"
}
"####,
            &ctx,
        )
        .expect("timestamps are saved as UTC: expected parses");
        assert_eq!(actual, expected, "timestamps are saved as UTC misrouted");
    }
    // vector: unknown sketch and row fields are preserved
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:10",
      "duration_seconds": 10,
      "narrative": "Open the app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:20",
      "narrative": "Locked narration.",
      "demo_actions": "Type a name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let actual = seam.round_trip(&sketch);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:10",
      "duration_seconds": 10,
      "narrative": "Open the app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:20",
      "narrative": "Locked narration.",
      "demo_actions": "Type a name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("unknown sketch and row fields are preserved: expected parses");
        assert_eq!(actual, expected, "unknown sketch and row fields are preserved misrouted");
    }
    // vector: unlocked cells on a row with a locked cell are editable
    {
        let sketch = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:10",
      "duration_seconds": 10,
      "narrative": "Open the app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:20",
      "narrative": "Locked narration.",
      "demo_actions": "Type a name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("sketch parses");
        let update = crate::model::RowTextUpdate::from_json(
            r####"
{
  "row_index": 1,
  "time": "0:25",
  "demo_actions": "Type the project name."
}
"####,
            &ctx,
        )
        .expect("update parses");
        let now: String = serde_json::from_str(
            r####"
"2026-07-01T09:30:00Z"
"####,
        )
        .expect("now parses");
        let actual = seam.update_row_text(&sketch, &update, &now);
        let expected = crate::model::Sketch::from_json(
            r####"
{
  "title": "Contract sketch",
  "locked": false,
  "description": null,
  "rows": [
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": "screenshots/open.png",
      "time": "0:10",
      "duration_seconds": 10,
      "narrative": "Open the app.",
      "demo_actions": "Click Open.",
      "motion_points": [
        {
          "rank": 1,
          "x": 0.5,
          "y": 0.25
        }
      ],
      "future_row_field": {
        "keep": true
      }
    },
    {
      "locked": false,
      "locks": {
        "time": false,
        "narrative": true,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:25",
      "narrative": "Locked narration.",
      "demo_actions": "Type the project name."
    },
    {
      "locked": true,
      "locks": {
        "time": false,
        "narrative": false,
        "demo_actions": false,
        "screenshot": false,
        "visual": false,
        "design_plan": false
      },
      "screenshot": null,
      "time": "0:30",
      "narrative": "Locked row.",
      "demo_actions": "Close."
    }
  ],
  "state": "draft",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-07-01T09:30:00Z",
  "future_document_field": [
    "still",
    "here"
  ]
}
"####,
            &ctx,
        )
        .expect("unlocked cells on a row with a locked cell are editable: expected parses");
        assert_eq!(actual, expected, "unlocked cells on a row with a locked cell are editable misrouted");
    }
    // skipped: visual lock also guards the screenshot — expectedError on a @sync op has no typed error channel
}
