pub mod agent;
pub mod agent_state;
pub mod animation;
pub mod automation;
pub mod diagnostics_sanitizer;
pub mod draftline_adapter;
pub mod export;
pub mod ffmpeg;
pub mod import;
pub mod interaction;
pub mod memory;
pub mod project;
pub mod recording;
#[cfg(target_os = "macos")]
pub(crate) mod recording_native_audio_macos;
#[cfg(target_os = "windows")]
pub(crate) mod recording_native_audio_windows;
#[cfg(target_os = "windows")]
pub(crate) mod recording_native_camera_windows;
#[cfg(target_os = "windows")]
pub(crate) mod recording_native_windows;
pub mod video_import;
