// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

mod planning_cell_locks_test;
mod motion_point_test;
mod typing_spot_test;
mod motion_plan_keyframe_test;
mod motion_plan_test;
mod narration_asset_test;
mod narration_beat_test;
mod narration_plan_test;
mod planning_row_test;
mod document_metadata_test;
mod sketch_test;
mod row_text_update_test;
mod vector_conformance_test;
