// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use crate::RowTextUpdate;
use crate::context::{LoadContext, SaveContext};

#[test]
fn test_row_text_update_load_json() {
    let json = r####"
{
  "row_index": 1
}
"####;
    let ctx = LoadContext::default();
    let result = RowTextUpdate::from_json(json, &ctx);
    assert!(result.is_ok(), "Failed to load from JSON: {:?}", result.err());
    let instance = result.unwrap();
    assert_eq!(instance.row_index, 1);
}

#[test]
fn test_row_text_update_load_yaml() {
    let yaml = r####"
row_index: 1

"####;
    let ctx = LoadContext::default();
    let result = RowTextUpdate::from_yaml(yaml, &ctx);
    assert!(result.is_ok(), "Failed to load from YAML: {:?}", result.err());
    let instance = result.unwrap();
    assert_eq!(instance.row_index, 1);
}

#[test]
fn test_row_text_update_roundtrip() {
    let json = r####"
{
  "row_index": 1
}
"####;
    let load_ctx = LoadContext::default();
    let result = RowTextUpdate::from_json(json, &load_ctx);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let save_ctx = SaveContext::default();
    let json_output = instance.to_json(&save_ctx);
    assert!(json_output.is_ok(), "Failed to serialize to JSON: {:?}", json_output.err());
}

#[cfg(feature = "serde")]
#[test]
fn test_row_text_update_serde_roundtrip() {
    let json = r####"
{
  "row_index": 1
}
"####;
    let instance: RowTextUpdate = serde_json::from_str(json)
        .expect("serde should deserialize canonical JSON");
    let value = serde_json::to_value(&instance)
        .expect("serde should serialize");
    let canonical: serde_json::Value = serde_json::from_str(json)
        .expect("canonical json parses");
    assert_eq!(value, instance.to_value(&SaveContext::default()), "serde serialize must equal canonical to_value");
    assert_eq!(instance, RowTextUpdate::load_from_value(&canonical, &LoadContext::default()), "serde deserialize must equal canonical load_from_value");
    assert_eq!(value, canonical, "serde must serialize to byte-identical canonical wire (empty-omission preserved; no plain-derive divergence)");
    let reparsed: RowTextUpdate = serde_json::from_value(value)
        .expect("serde should re-deserialize");
    assert_eq!(instance, reparsed, "serde round-trip must be stable");
}

#[test]
fn test_row_text_update_from_json_invalid() {
    let ctx = LoadContext::default();
    assert!(RowTextUpdate::from_json("{", &ctx).is_err(), "malformed JSON must be rejected instead of silently defaulting");
}
