// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use crate::Sketch;
use crate::SketchState;
use crate::context::{LoadContext, SaveContext};

#[test]
fn test_sketch_load_json() {
    let json = r####"
{
  "title": "Intro",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "rows": [
    {
      "time": "0:20",
      "narrative": "Welcome to CutReady.",
      "demo_actions": "Open the workspace."
    }
  ]
}
"####;
    let ctx = LoadContext::default();
    let result = Sketch::from_json(json, &ctx);
    assert!(result.is_ok(), "Failed to load from JSON: {:?}", result.err());
    let instance = result.unwrap();
    assert_eq!(instance.title, "Intro");
    assert_eq!(instance.created_at, "2026-06-28T20:00:00Z");
    assert_eq!(instance.updated_at, "2026-06-28T20:20:00Z");
}

#[test]
fn test_sketch_load_yaml() {
    let yaml = r####"
title: Intro
created_at: "2026-06-28T20:00:00Z"
updated_at: "2026-06-28T20:20:00Z"
rows:
  - time: "0:20"
    narrative: Welcome to CutReady.
    demo_actions: Open the workspace.

"####;
    let ctx = LoadContext::default();
    let result = Sketch::from_yaml(yaml, &ctx);
    assert!(result.is_ok(), "Failed to load from YAML: {:?}", result.err());
    let instance = result.unwrap();
    assert_eq!(instance.title, "Intro");
    assert_eq!(instance.created_at, "2026-06-28T20:00:00Z");
    assert_eq!(instance.updated_at, "2026-06-28T20:20:00Z");
}

#[test]
fn test_sketch_roundtrip() {
    let json = r####"
{
  "title": "Intro",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "rows": [
    {
      "time": "0:20",
      "narrative": "Welcome to CutReady.",
      "demo_actions": "Open the workspace."
    }
  ]
}
"####;
    let load_ctx = LoadContext::default();
    let result = Sketch::from_json(json, &load_ctx);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let save_ctx = SaveContext::default();
    let json_output = instance.to_json(&save_ctx);
    assert!(json_output.is_ok(), "Failed to serialize to JSON: {:?}", json_output.err());
}

#[cfg(feature = "serde")]
#[test]
fn test_sketch_serde_roundtrip() {
    let json = r####"
{
  "title": "Intro",
  "created_at": "2026-06-28T20:00:00Z",
  "updated_at": "2026-06-28T20:20:00Z",
  "rows": [
    {
      "time": "0:20",
      "narrative": "Welcome to CutReady.",
      "demo_actions": "Open the workspace."
    }
  ]
}
"####;
    let instance: Sketch = serde_json::from_str(json)
        .expect("serde should deserialize canonical JSON");
    let value = serde_json::to_value(&instance)
        .expect("serde should serialize");
    let canonical: serde_json::Value = serde_json::from_str(json)
        .expect("canonical json parses");
    assert_eq!(value, instance.to_value(&SaveContext::default()), "serde serialize must equal canonical to_value");
    assert_eq!(instance, Sketch::load_from_value(&canonical, &LoadContext::default()), "serde deserialize must equal canonical load_from_value");
    let reparsed: Sketch = serde_json::from_value(value)
        .expect("serde should re-deserialize");
    assert_eq!(instance, reparsed, "serde round-trip must be stable");
}

#[test]
fn test_sketch_from_json_invalid() {
    let ctx = LoadContext::default();
    assert!(Sketch::from_json("{", &ctx).is_err(), "malformed JSON must be rejected instead of silently defaulting");
}
