// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use crate::TypingSpot;
use crate::context::{LoadContext, SaveContext};

#[test]
fn test_typing_spot_load_json() {
    let json = r####"
{
  "x": 1.5,
  "y": 1.5,
  "width": 1.5,
  "height": 1.5,
  "text": "sample"
}
"####;
    let ctx = LoadContext::default();
    let result = TypingSpot::from_json(json, &ctx);
    assert!(result.is_ok(), "Failed to load from JSON: {:?}", result.err());
    let instance = result.unwrap();
    assert_eq!(instance.x, 1.5);
    assert_eq!(instance.y, 1.5);
    assert_eq!(instance.width, 1.5);
    assert_eq!(instance.height, 1.5);
    assert_eq!(instance.text, "sample");
}

#[test]
fn test_typing_spot_load_yaml() {
    let yaml = r####"
x: 1.5
y: 1.5
width: 1.5
height: 1.5
text: sample

"####;
    let ctx = LoadContext::default();
    let result = TypingSpot::from_yaml(yaml, &ctx);
    assert!(result.is_ok(), "Failed to load from YAML: {:?}", result.err());
    let instance = result.unwrap();
    assert_eq!(instance.x, 1.5);
    assert_eq!(instance.y, 1.5);
    assert_eq!(instance.width, 1.5);
    assert_eq!(instance.height, 1.5);
    assert_eq!(instance.text, "sample");
}

#[test]
fn test_typing_spot_roundtrip() {
    let json = r####"
{
  "x": 1.5,
  "y": 1.5,
  "width": 1.5,
  "height": 1.5,
  "text": "sample"
}
"####;
    let load_ctx = LoadContext::default();
    let result = TypingSpot::from_json(json, &load_ctx);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let save_ctx = SaveContext::default();
    let json_output = instance.to_json(&save_ctx);
    assert!(json_output.is_ok(), "Failed to serialize to JSON: {:?}", json_output.err());
}

#[cfg(feature = "serde")]
#[test]
fn test_typing_spot_serde_roundtrip() {
    let json = r####"
{
  "x": 1.5,
  "y": 1.5,
  "width": 1.5,
  "height": 1.5,
  "text": "sample"
}
"####;
    let instance: TypingSpot = serde_json::from_str(json)
        .expect("serde should deserialize canonical JSON");
    let value = serde_json::to_value(&instance)
        .expect("serde should serialize");
    let canonical: serde_json::Value = serde_json::from_str(json)
        .expect("canonical json parses");
    assert_eq!(value, instance.to_value(&SaveContext::default()), "serde serialize must equal canonical to_value");
    assert_eq!(instance, TypingSpot::load_from_value(&canonical, &LoadContext::default()), "serde deserialize must equal canonical load_from_value");
    let reparsed: TypingSpot = serde_json::from_value(value)
        .expect("serde should re-deserialize");
    assert_eq!(instance, reparsed, "serde round-trip must be stable");
}

#[test]
fn test_typing_spot_from_json_invalid() {
    let ctx = LoadContext::default();
    assert!(TypingSpot::from_json("{", &ctx).is_err(), "malformed JSON must be rejected instead of silently defaulting");
}
